### ISSUE TITLE
[Auth UI] Not able to back to email / phone number input page after inputting an invalid verification code

### ISSUE THREAD

**Issue by keithtkl** [SkygearIO/skygear-server#1489] opened 2020-06-05 04:10 UTC
User still stays on the verification code page after inputted an invalid code and pressed back button on the page 
- Skygear Server Date/Version: Not sure
- Application Platform: Tested on Rees

#### Expected Results
Press on the back button should open the phone / email input page so that user can make the change

#### Actual Results
Pressing on the back button still stays on the verification code input page

#### Steps to reproduce
1. Open signup / login page, and use email / phone number
2. On verification code page, fill in an invalid code and click Next
3. Press back button on the page after seeing the error message
4. Still stay on the verification page

**Comment by louischan-oursky** [comment] 2020-06-05 04:13
This problem is about the interaction between Post/Redirect/Get pattern and the browser history.

**Comment by louischan-oursky** [comment] 2020-06-05 04:15
duplicate of #1481

**Closed** 2020-06-05 11:07 UTC
Labels: authgear, bug/major
