### ISSUE TITLE
Push Notifications don't receive in chat 

### ISSUE THREAD

**Issue by KhaledAld** [SkygearIO/skygear-server#643] opened 2018-09-02 08:44 UTC
Hi 
i use skygear to make chat server  and i use skygear portal with my app (larsa)
when send message from Device A to Device B , Device B dont receive any Notification.
but when i send notification manually from Device A to Device B the message is received to Device B 

What can i do to enable `push Notifications` in message

**Comment by tensiuyan** [comment] 2018-09-03 07:30
@KhaledAld to send a push notification to the devices when there are new messages you need to register an afterMessageSentHook. Here's the doc: https://docs.skygear.io/guides/chat/cloud-event-hook/js/. Scroll to the bottom and you will find an example. 

Closing this issue since it is not a bug. Please reach us on https://discuss.skygear.io/ for support. Thanks!

**Closed by tensiuyan** 2018-09-03 07:30 UTC
