### ISSUE TITLE
skygear server is working slow on local deployment

### ISSUE THREAD

**Issue by KhaledAld** [SkygearIO/skygear-server#676] opened 2018-09-19 12:55 UTC
Hi There,

I'm using skygear on my local server and everything works fine.
but Socket is dorp every to second (for example) and chat is working too slowly

any suggestion ??

Thanks

**Comment by tensiuyan** [comment] 2018-09-20 07:01
Hello @KhaledAld for support please reach us over [Skygear forum](https://discuss.skygear.io) or [Slack](https://slack.skygear.io).

Closing this issue as this is not a bug report.

**Closed** 2018-09-20 07:01 UTC
