### ISSUE TITLE
Cannot sign asset with master key

### ISSUE THREAD

**Issue by cychiuae** [SkygearIO/skygear-server#1455] opened 2020-05-28 03:41 UTC
- Skygear Server Date/Version: d2a82c2
- [x] Is this a regression?

#### Expected Results
Can sign asset 

#### Actual Results
401 error

#### Steps to reproduce
Call sign asset api with master key

**Comment by louischan-oursky** [comment] 2020-05-28 03:54
Duplicate of https://github.com/SkygearIO/skygear-server/issues/1456

**Closed** 2020-06-03 03:42 UTC
