### ISSUE TITLE
Enable push  notification in local

### ISSUE THREAD

**Issue by KhaledAld** [SkygearIO/skygear-server#641] opened 2018-08-30 09:38 UTC
Hi 
i'm working on run skysearver as virtual box from docker-compose.yml file.
how to enable push notifications  , and where is the path of APNS Certificate (.pem file) ?

**Comment by tensiuyan** [comment] 2018-09-06 03:38
@KhaledAld please refer to this discussion thread: https://discuss.skygear.io/t/example-for-skygear-environment-variables/157/2

closing this issue since this is not a bug report.

**Closed by tensiuyan** 2018-09-06 03:38 UTC
